imports:
    - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusShopBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusApiBundle/Resources/config/app/config.yaml" }
    - { resource: "@SyliusPayumBundle/Resources/config/app/config.yaml" }
    - { resource: "@SyliusPayPalPlugin/config/config.yaml" }

parameters:
    fixtures_dir: "%kernel.project_dir%/src/Resources/fixtures"
    sylius_core.public_dir: '%kernel.project_dir%/public'
    sylius.cache:
        type: array
    sylius_refund.supported_gateways:
        - offline
        - mollie

sylius_shop:
    product_grid:
        include_all_descendants: true

sylius_api:
    enabled: true

sylius_theme:
    sources:
        filesystem:
            directories:
                - "%kernel.project_dir%/themes"

sylius_order:
    resources:
        order:
            classes:
                model: App\Entity\Order\Order
        order_item:
            classes:
                model: App\Entity\Order\OrderItem

sylius_payment:
    resources:
        gateway_config:
            classes:
                model: App\Entity\Payment\GatewayConfig

sylius_product:
    resources:
        product:
            classes:
                model: App\Entity\Product\Product
        product_variant:
            classes:
                model: App\Entity\Product\ProductVariant

sylius_user:
    resources:
        admin:
            user:
                classes:
                    model: App\Entity\User\AdminUser

