sylius_twig_hooks:
    hooks:
        'sylius_admin.base#stylesheets':
            app_styles:
                template: 'admin/stylesheets.html.twig'
        'sylius_admin.base#javascripts':
            app_javascripts:
                template: 'admin/javascripts.html.twig'
            override:
                template: "css_override.html.twig"
                priority: -10

        'sylius_admin.security.login':
            info_box:
                template: "info_box.html.twig"
                priority: 100

        'sylius_admin.security.login.page.content':
            info_box:
                template: "admin_demo_credentials.html.twig"
                priority: 150

        'sylius_admin.common.index':
            info_box:
                template: "info_box.html.twig"
                priority: 100


        'sylius_shop.base#stylesheets':
            analytics:
                template: "analytics.html.twig"
                priority: 100
            app_styles:
                template: 'shop/stylesheets.html.twig'
        'sylius_shop.base#javascripts':
            app_javascripts:
                template: 'shop/javascripts.html.twig'
            override:
                template: "css_override.html.twig"
                priority: -10

        'sylius_shop.base#metatags':
            homepage_metatags:
                template: "shop_metatags.html.twig"
                priority: 150

        'sylius_shop.homepage.index#metatags':
            homepage_metatags:
                template: "homepage_metatags.html.twig"
                priority: 150

        'sylius_shop.base.offcanvas':
            info_box:
                template: "info_box.html.twig"
                priority: 100

        'sylius_shop.account.login.content.login_container':
            analytics:
                template: "shop_demo_credentials.html.twig"
                priority: 150

        'sylius_shop.homepage.index':
            banner:
                template: '@SyliusShop/homepage/banner.html.twig'
                priority: 300
            latest_deals:
                component: 'sylius_shop:product:list'
                props:
                    limit: 4
                    template: '@SyliusShop/homepage/list_deals.html.twig'
                configuration:
                    title: 'sylius.homepage.latest_deals'
                    test_attribute: 'latest-deals'
                priority: 200
            latest_products:
                component: 'sylius_shop:product:list'
                props:
                    limit: 8
                    template: '@SyliusShop/homepage/list_products.html.twig'
                priority: 0

        'sylius_shop.base.footer.content':
            payment_methods:
                template: 'payment_methods.html.twig'
                priority: 100
        'sylius_shop.base.header.navbar.menu':
            blog_item:
                template: 'shop/header/navbar/menu/blog_item.html.twig'
                priority: -100
            faq_item:
                template: 'shop/header/navbar/menu/faq_item.html.twig'
                priority: -200

#        'sylius_shop.homepage.index':
#            banner:
#                enabled: false
#            latest_deals:
#                enabled: false
#            new_collection:
#                enabled: false
#            latest_products:
#                enabled: false
#            container:
#                template: 'shop/homepage/index/container.html.twig'

        'sylius_shop.homepage.index.container':
            homepage_textarea:
                component: 'sylius_cms:shop:render:block'
                props:
                    code: 'homepage_textarea'
                priority: 800
            homepage_banner_1:
                component: 'sylius_cms:shop:render:block'
                props:
                    code: 'homepage_banner_1'
                priority: 700
            homepage_products_carousel:
                component: 'sylius_cms:shop:render:block'
                props:
                    code: 'homepage_products_carousel'
                priority: 600
            homepage_taxons_list:
                component: 'sylius_cms:shop:render:block'
                props:
                    code: 'homepage_taxons_list'
                priority: 500
            homepage_products_grid:
                component: 'sylius_cms:shop:render:block'
                props:
                    code: 'homepage_products_grid'
                priority: 400
            homepage_banner_2:
                component: 'sylius_cms:shop:render:block'
                props:
                    code: 'homepage_banner_2'
                priority: 300
            homepage_products_carousel_by_taxon:
                component: 'sylius_cms:shop:render:block'
                props:
                    code: 'homepage_products_carousel_by_taxon'
                priority: 200
            homepage_banner_3:
                component: 'sylius_cms:shop:render:block'
                props:
                    code: 'homepage_banner_3'
                priority: 100
            homepage_products_grid_by_taxon:
                component: 'sylius_cms:shop:render:block'
                props:
                    code: 'homepage_products_grid_by_taxon'
                priority: 0

        'sylius_shop.product.show.content':
            black_friday_banner_product:
                component: 'sylius_cms:shop:render:block'
                props:
                    code: 'black_friday_banner_product'
                priority: 150
            product_listing:
                enabled: false
            specified_products_in_taxons:
                component: 'sylius_cms:shop:render:block'
                props:
                    code: 'specified_products_in_taxons'
                priority: -100

        'sylius_shop.product.index.content.body.main.header':
            black_friday_banner_taxon:
                component: 'sylius_cms:shop:render:block'
                props:
                    code: 'black_friday_banner_taxon'
                priority: -100
