sylius_twig_hooks:
    hooks:
        'sylius_admin.base#stylesheets':
            app_styles:
                template: 'admin/stylesheets.html.twig'
        'sylius_admin.base#javascripts':
            app_javascripts:
                template: 'admin/javascripts.html.twig'
            override:
                template: "css_override.html.twig"
                priority: -10

        'sylius_admin.security.login':
            info_box:
                template: "info_box.html.twig"
                priority: 100

        'sylius_admin.security.login.page.content':
            info_box:
                template: "admin_demo_credentials.html.twig"
                priority: 150

        'sylius_admin.common.index':
            info_box:
                template: "info_box.html.twig"
                priority: 100


        'sylius_shop.base#stylesheets':
            analytics:
                template: "analytics.html.twig"
                priority: 100
            app_styles:
                template: 'shop/stylesheets.html.twig'
        'sylius_shop.base#javascripts':
            app_javascripts:
                template: 'shop/javascripts.html.twig'
            override:
                template: "css_override.html.twig"
                priority: -10

        'sylius_shop.base#metatags':
            homepage_metatags:
                template: "shop_metatags.html.twig"
                priority: 150

        'sylius_shop.homepage.index#metatags':
            homepage_metatags:
                template: "homepage_metatags.html.twig"
                priority: 150

        'sylius_shop.base.offcanvas':
            info_box:
                template: "info_box.html.twig"
                priority: 100

        'sylius_shop.account.login.content.login_container':
            analytics:
                template: "shop_demo_credentials.html.twig"
                priority: 150

        'sylius_shop.base.footer.content':
            payment_methods:
                template: 'payment_methods.html.twig'
                priority: 100
        'sylius_admin.payment_method.update.content.form.sections.gateway_configuration.mollie.credentials':
            test_credentials:
                enabled: false
            api_key_live:
                enabled: false
            test_api_keys_action:
                enabled: false

        'sylius_admin.payment_method.update.content.form.sections.gateway_configuration.mollie_subscription.credentials':
            test_credentials:
                enabled: false
            api_key_live:
                enabled: false
            test_api_keys_action:
                enabled: false

        'sylius_admin.payment_method.update.content.form.sections.gateway_configuration.sylius_paypal':
            client_id:
                enabled: false
            client_secret:
                enabled: false
            reports_sftp_username:
                enabled: false
            reports_sftp_password:
                enabled: false
