# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en_US
    app.demo_mode: '%env(bool:APP_DEMO_MODE)%'

services:
    App\EventListener\AdminListener:
        arguments: [ '@request_stack' ]
        tags:
            - { name: kernel.event_listener, event: sylius.admin_user.pre_delete, method: preDelete }
            - { name: kernel.event_listener, event: sylius.admin_user.pre_update, method: preUpdate }

    App\EventListener\PaymentMethodListener:
        arguments: [ '@request_stack', '@router' ]
        tags:
            - { name: kernel.event_listener, event: kernel.request , method: preCreate }

    App\EventListener\ChannelListener:
        arguments: [ '@request_stack', '@router' ]
        tags:
            - { name: kernel.event_listener, event: kernel.request , method: preCreate }

    App\EventListener\UserRegistrationListener:
        class: App\EventListener\UserRegistrationListener
        arguments: [ '@request_stack', '@App\Generator\FlashMessageGeneratorInterface' ]
        tags:
            - { name: kernel.event_listener, event: sylius.user.email_verification.token , method: addVerificationLink }

    App\Generator\FlashMessageGeneratorInterface:
        class: App\Generator\VerificationFlashMessageGenerator
        arguments: ['@router', '@translator.default']

    App\Controller\CompleteDemoPayPalPaymentAction:
        arguments:
            $demoMode: '%app.demo_mode%'
            $paymentRepository: '@sylius.repository.payment'
            $csrfTokenManager: '@security.csrf.token_manager'
            $orderProvider: '@Sylius\PayPalPlugin\Provider\OrderProviderInterface'
            $capturePaymentResolver: '@Sylius\PayPalPlugin\Resolver\CapturePaymentResolverInterface'
            $paymentStateManager: '@Sylius\PayPalPlugin\Manager\PaymentStateManagerInterface'
            $stateMachine: '@Sylius\Abstraction\StateMachine\StateMachineInterface'
            $urlGenerator: '@router'
            $entityManager: '@doctrine.orm.entity_manager'
        tags: ['controller.service_arguments']

    App\Form\Extension\MollieGatewayConfigurationTypeExtension:
        class: App\Form\Extension\MollieGatewayConfigurationTypeExtension
        tags:
            - { name: form.type_extension }

    App\Form\Extension\PayPalConfigurationTypeExtension:
        class: App\Form\Extension\PayPalConfigurationTypeExtension
        tags:
            - { name: form.type_extension }

    sylius.http_client:
        class: GuzzleHttp\Client

twig:
    globals:
        app_demo_mode: '%app.demo_mode%'
